// Auto-generated by scripts/sync-content.ts — do not edit.
// Standalone drill count for the home banner. Importing drills.ts
// pulls ~260kB of scenario content into the home page bundle.
export const DRILL_COUNT = 27;
